services:
  - type: web
    name: cobalt-api
    env: docker
    plan: starter
    dockerfilePath: ./api/Dockerfile
    envVars:
      API_URL: https://cobalt-4zjz.onrender.com/api
      # Add other environment variables as needed

  - type: web
    name: cobalt-web
    env: docker
    plan: starter
    dockerfilePath: ./web/Dockerfile
    envVars:
      REACT_APP_API_URL: https://cobalt-4zjz.onrender.com/api
      # Add other environment variables as needed
